image: node:14

pipelines:
  default:
    - step:
        name: Acessar EC2 via SSH
        services:
          - docker
        caches:
          - docker
        script:
          - apt-get update && apt-get install -y openssh-client curl
          - cd ~
          - curl -O https://mybp-dev.s3.amazonaws.com/mybpin.pem
          - chmod 400 mybpin.pem
          - pwd
          - ls -la
          - ssh -i "${PWD}/mybpin.pem" "${USER_MYBP}@${HOST_HOMOL}" touch arquivobitbucket.txt
    - step:
        name: Teste
        script:
          - echo "Teste executado com sucesso"
