UPDATE `habilidades` SET `nome` = 'configuracao_habilidades', `descricao` = 'Acessar rota/menu habilidades' WHERE `id` = 1;
UPDATE `habilidades` SET `nome` = 'configuracao_habilidades_insert', `descricao` = 'Pode inserir uma nova habilidade' WHERE `id` = 2;
UPDATE `habilidades` SET `nome` = 'configuracao_habilidades_update', `descricao` = 'Pode alterar uma habilidade' WHERE `id` = 3;
UPDATE `habilidades` SET `nome` = 'configuracao_habilidades_delete', `descricao` = 'Pode apagar uma habilidade' WHERE `id` = 4;
UPDATE `habilidades` SET `nome` = 'configuracao_papel', `descricao` = 'Acessar rota/menu papeis' WHERE `id` = 5;
UPDATE `habilidades` SET `nome` = 'configuracao_papel_insert', `descricao` = 'Pode cadastrar um papel' WHERE `id` = 6;
UPDATE `habilidades` SET `nome` = 'configuracao_papel_update', `descricao` = 'Pode alterar um papel' WHERE `id` = 7;
UPDATE `habilidades` SET `nome` = 'configuracao_papel_delete', `descricao` = 'Pode apagar um papel' WHERE `id` = 8;
UPDATE `habilidades` SET `nome` = 'usuario_usuarios', `descricao` = 'Acessar rota/menu usuários' WHERE `id` = 9;
UPDATE `habilidades` SET `nome` = 'usuario_usuarios_insert', `descricao` = 'Pode cadastrar um usuário' WHERE `id` = 10;
UPDATE `habilidades` SET `nome` = 'usuario_usuarios_update', `descricao` = 'Pode alterar um usuário' WHERE `id` = 11;
UPDATE `habilidades` SET `nome` = 'usuario_usuarios_delete', `descricao` = 'Pode apagar um usuário' WHERE `id` = 12;
UPDATE `habilidades` SET `nome` = 'usuario_alterar-senha', `descricao` = 'Pode alterar sua propria senha de acesso ao sistema' WHERE `id` = 13;
UPDATE `habilidades` SET `nome` = 'administracao_clientes', `descricao` = 'Acessar rota/menu clientes' WHERE `id` = 14;
UPDATE `habilidades` SET `nome` = 'administracao_clientes_insert', `descricao` = 'Pode cadastrar um cliente' WHERE `id` = 15;
UPDATE `habilidades` SET `nome` = 'administracao_clientes_update', `descricao` = 'Pode alterar um cliente' WHERE `id` = 16;
UPDATE `habilidades` SET `nome` = 'administracao_clientes_delete', `descricao` = 'Pode apagar um cliente' WHERE `id` = 17;
UPDATE `habilidades` SET `nome` = 'curriculos_recrutamento', `descricao` = 'Acessar rota/menu Recrutamento' WHERE `id` = 18;
UPDATE `habilidades` SET `nome` = 'curriculos_recrutamento_insert', `descricao` = 'Pode cadastrar um Recrutamento' WHERE `id` = 19;
UPDATE `habilidades` SET `nome` = 'curriculos_recrutamento_update', `descricao` = 'Pode alterar um Recrutamento' WHERE `id` = 20;
UPDATE `habilidades` SET `nome` = 'curriculos_recrutamento_delete', `descricao` = 'Pode apagar um Recrutamento' WHERE `id` = 21;
UPDATE `habilidades` SET `nome` = 'feedback_curriculos', `descricao` = 'Acessar rota/menu Feedback Curriculos' WHERE `id` = 22;
UPDATE `habilidades` SET `nome` = 'feedback_curriculos_insert', `descricao` = 'Pode cadastrar um Feedback Curriculo' WHERE `id` = 23;
UPDATE `habilidades` SET `nome` = 'feedback_curriculos_update', `descricao` = 'Pode alterar um Feedback Curriculo' WHERE `id` = 24;
UPDATE `habilidades` SET `nome` = 'feedback_curriculos_delete', `descricao` = 'Pode apagar um Feedback Curriculo' WHERE `id` = 25;
UPDATE `habilidades` SET `nome` = 'entrevista_parecer_rh', `descricao` = 'Acessar rota/menu Parecer Rh' WHERE `id` = 26;
UPDATE `habilidades` SET `nome` = 'entrevista_parecer_rh_insert', `descricao` = 'Pode cadastrar um Parecer Rh' WHERE `id` = 27;
UPDATE `habilidades` SET `nome` = 'entrevista_parecer_rh_update', `descricao` = 'Pode alterar um Parecer Rh' WHERE `id` = 28;
UPDATE `habilidades` SET `nome` = 'entrevista_parecer_rh_delete', `descricao` = 'Pode apagar um Parecer Rh' WHERE `id` = 29;
UPDATE `habilidades` SET `nome` = 'entrevista_parecer_rota', `descricao` = 'Acessar rota/menu Parecer Rota Transporte' WHERE `id` = 30;
UPDATE `habilidades` SET `nome` = 'entrevista_parecer_rota_insert', `descricao` = 'Pode cadastrar um Parecer Rota Transporte' WHERE `id` = 31;
UPDATE `habilidades` SET `nome` = 'entrevista_parecer_rota_update', `descricao` = 'Pode alterar um Parecer Rota Transporte' WHERE `id` = 32;
UPDATE `habilidades` SET `nome` = 'entrevista_parecer_rota_delete', `descricao` = 'Pode apagar um Parecer Rota Transporte' WHERE `id` = 33;
UPDATE `habilidades` SET `nome` = 'entrevista_parecer_teste_pratico', `descricao` = 'Acessar rota/menu Parecer Teste Prático' WHERE `id` = 34;
UPDATE `habilidades` SET `nome` = 'entrevista_parecer_teste_pratico_insert', `descricao` = 'Pode cadastrar um Parecer Teste Prático' WHERE `id` = 35;
UPDATE `habilidades` SET `nome` = 'entrevista_parecer_teste_pratico_update', `descricao` = 'Pode alterar um Parecer Teste Prático' WHERE `id` = 36;
UPDATE `habilidades` SET `nome` = 'entrevista_parecer_teste_pratico_delete', `descricao` = 'Pode apagar um Parecer Teste Prático' WHERE `id` = 37;
UPDATE `habilidades` SET `nome` = 'entrevista_parecer_entrevista', `descricao` = 'Acessar rota/menu Parecer Entrevistas Técnicas' WHERE `id` = 38;
UPDATE `habilidades` SET `nome` = 'entrevista_parecer_entrevista_insert', `descricao` = 'Pode cadastrar um Parecer Entrevista Técnica' WHERE `id` = 39;
UPDATE `habilidades` SET `nome` = 'entrevista_parecer_entrevista_update', `descricao` = 'Pode alterar um Parecer Entrevista Técnica' WHERE `id` = 40;
UPDATE `habilidades` SET `nome` = 'entrevista_parecer_entrevista_delete', `descricao` = 'Pode apagar um Parecer Entrevista Técnica' WHERE `id` = 41;
UPDATE `habilidades` SET `nome` = 'entrevista_resultado_integrado', `descricao` = 'Acessar rota/menu Resultados Integrados' WHERE `id` = 42;
UPDATE `habilidades` SET `nome` = 'entrevista_resultado_integrado_insert', `descricao` = 'Pode cadastrar um Resultado' WHERE `id` = 43;
UPDATE `habilidades` SET `nome` = 'entrevista_resultado_integrado_update', `descricao` = 'Pode alterar um Resultado' WHERE `id` = 44;
UPDATE `habilidades` SET `nome` = 'entrevista_resultado_integrado_delete', `descricao` = 'Pode apagar um Resultado' WHERE `id` = 45;
UPDATE `habilidades` SET `nome` = 'admissao_processo', `descricao` = 'Acessar rota/menu Admissões' WHERE `id` = 46;
UPDATE `habilidades` SET `nome` = 'admissao_processo_insert', `descricao` = 'Pode cadastrar um Admissão' WHERE `id` = 47;
UPDATE `habilidades` SET `nome` = 'admissao_processo_update', `descricao` = 'Pode alterar um Admissão' WHERE `id` = 48;
UPDATE `habilidades` SET `nome` = 'admissao_processo_delete', `descricao` = 'Pode apagar um Admissão' WHERE `id` = 49;
UPDATE `habilidades` SET `nome` = 'cloud', `descricao` = 'Acessar rota/menu Cloud' WHERE `id` = 50;
UPDATE `habilidades` SET `nome` = 'cloud_insert', `descricao` = 'Pode cadastrar um Cloud' WHERE `id` = 51;
UPDATE `habilidades` SET `nome` = 'cloud_update', `descricao` = 'Pode alterar um Cloud' WHERE `id` = 52;
UPDATE `habilidades` SET `nome` = 'cloud_delete', `descricao` = 'Pode apagar um Cloud' WHERE `id` = 53;
UPDATE `habilidades` SET `nome` = 'cloud_bpse', `descricao` = 'Acessar rota/menu Cloud BPSE' WHERE `id` = 54;
UPDATE `habilidades` SET `nome` = 'cloud_bpse_insert', `descricao` = 'Pode cadastrar um Cloud BPSE' WHERE `id` = 55;
UPDATE `habilidades` SET `nome` = 'cloud_bpse_update', `descricao` = 'Pode alterar um Cloud BPSE' WHERE `id` = 56;
UPDATE `habilidades` SET `nome` = 'cloud_bpse_delete', `descricao` = 'Pode apagar um Cloud BPSE' WHERE `id` = 57;
UPDATE `habilidades` SET `nome` = 'cloud_clientes', `descricao` = 'Acessar rota/menu Cloud Clientes' WHERE `id` = 58;
UPDATE `habilidades` SET `nome` = 'cloud_clientes_insert', `descricao` = 'Pode cadastrar um Cloud Clientes' WHERE `id` = 59;
UPDATE `habilidades` SET `nome` = 'cloud_clientes_update', `descricao` = 'Pode alterar um Cloud Clientes' WHERE `id` = 60;
UPDATE `habilidades` SET `nome` = 'cloud_clientes_delete', `descricao` = 'Pode apagar um Cloud Clientes' WHERE `id` = 61;
UPDATE `habilidades` SET `nome` = 'cloud_publica', `descricao` = 'Acessar rota/menu Cloud Pública' WHERE `id` = 62;
UPDATE `habilidades` SET `nome` = 'cloud_publica_insert', `descricao` = 'Pode cadastrar um Cloud Pública' WHERE `id` = 63;
UPDATE `habilidades` SET `nome` = 'cloud_publica_update', `descricao` = 'Pode alterar um Cloud Pública' WHERE `id` = 64;
UPDATE `habilidades` SET `nome` = 'cloud_publica_delete', `descricao` = 'Pode apagar um Cloud Pública' WHERE `id` = 65;
UPDATE `habilidades` SET `nome` = 'cloud_configuracoes', `descricao` = 'Acessar rota/menu Cloud Configurações' WHERE `id` = 66;
UPDATE `habilidades` SET `nome` = 'cloud_configuracoes_insert', `descricao` = 'Pode cadastrar um Cloud Configurações' WHERE `id` = 67;
UPDATE `habilidades` SET `nome` = 'cloud_configuracoes_update', `descricao` = 'Pode alterar um Cloud Configurações' WHERE `id` = 68;
UPDATE `habilidades` SET `nome` = 'cloud_configuracoes_delete', `descricao` = 'Pode apagar um Cloud Configurações' WHERE `id` = 69;
UPDATE `habilidades` SET `nome` = 'site_galeria_site', `descricao` = 'Acessar rota/menu Site - Galeria' WHERE `id` = 70;
UPDATE `habilidades` SET `nome` = 'site_galeria_site_insert', `descricao` = 'Pode cadastrar uma Galeria' WHERE `id` = 71;
UPDATE `habilidades` SET `nome` = 'site_galeria_site_update', `descricao` = 'Pode alterar uma Galeria' WHERE `id` = 72;
UPDATE `habilidades` SET `nome` = 'site_galeria_site_delete', `descricao` = 'Pode apagar uma Galeria' WHERE `id` = 73;
UPDATE `habilidades` SET `nome` = 'site_cartela_cliente_site', `descricao` = 'Acessar rota/menu Site - Cartela Cliente' WHERE `id` = 74;
UPDATE `habilidades` SET `nome` = 'site_cartela_cliente_site_insert', `descricao` = 'Pode cadastrar uma Cartela Cliente' WHERE `id` = 75;
UPDATE `habilidades` SET `nome` = 'site_cartela_cliente_site_update', `descricao` = 'Pode alterar uma Cartela Cliente' WHERE `id` = 76;
UPDATE `habilidades` SET `nome` = 'site_cartela_cliente_site_delete', `descricao` = 'Pode apagar uma Cartela Cliente' WHERE `id` = 77;
UPDATE `habilidades` SET `nome` = 'site_depoimento_site', `descricao` = 'Acessar rota/menu Site - Depoimento' WHERE `id` = 78;
UPDATE `habilidades` SET `nome` = 'site_depoimento_site_insert', `descricao` = 'Pode cadastrar um Depoimento' WHERE `id` = 79;
UPDATE `habilidades` SET `nome` = 'site_depoimento_site_update', `descricao` = 'Pode alterar um Depoimento' WHERE `id` = 80;
UPDATE `habilidades` SET `nome` = 'site_depoimento_site_delete', `descricao` = 'Pode apagar um Depoimento' WHERE `id` = 81;
UPDATE `habilidades` SET `nome` = 'cadastro_vagas', `descricao` = 'Acessar rota/menu Administracao - Vagas' WHERE `id` = 82;
UPDATE `habilidades` SET `nome` = 'cadastro_vagas_insert', `descricao` = 'Pode cadastrar uma vaga' WHERE `id` = 83;
UPDATE `habilidades` SET `nome` = 'cadastro_vagas_update', `descricao` = 'Pode alterar uma vaga' WHERE `id` = 84;
UPDATE `habilidades` SET `nome` = 'cadastro_vagas_abertas', `descricao` = 'Acessar rota/menu Vagas Abertas' WHERE `id` = 85;
UPDATE `habilidades` SET `nome` = 'cadastro_vagas_abertas_insert', `descricao` = 'Pode cadastrar uma vaga aberta' WHERE `id` = 86;
UPDATE `habilidades` SET `nome` = 'cadastro_vagas_abertas_update', `descricao` = 'Pode alterar uma vaga aberta' WHERE `id` = 87;
UPDATE `habilidades` SET `nome` = 'treinamento_carteira-etiquetas', `descricao` = 'Acessar rota/menu Treinamentos' WHERE `id` = 88;
UPDATE `habilidades` SET `nome` = 'treinamento_carteira-etiquetas_insert', `descricao` = 'Pode cadastrar um treinamento' WHERE `id` = 89;
UPDATE `habilidades` SET `nome` = 'treinamento_carteira-etiquetas_update', `descricao` = 'Pode alterar um treinamento' WHERE `id` = 90;
UPDATE `habilidades` SET `nome` = 'treinamento_envio', `descricao` = 'Pode enviar por email ou imprimir' WHERE `id` = 91;
UPDATE `habilidades` SET `nome` = 'administracao_fornecedores', `descricao` = 'Acessar rota/menu Fornecedores' WHERE `id` = 92;
UPDATE `habilidades` SET `nome` = 'administracao_fornecedores_insert', `descricao` = 'Pode cadastrar um Fornecedor' WHERE `id` = 93;
UPDATE `habilidades` SET `nome` = 'administracao_fornecedores_update', `descricao` = 'Pode alterar um Fornecedor' WHERE `id` = 94;
UPDATE `habilidades` SET `nome` = 'administracao_fornecedores_delete', `descricao` = 'Pode apagar um Fornecedor' WHERE `id` = 95;
UPDATE `habilidades` SET `nome` = 'treinamento_portaria', `descricao` = 'Acessar rota/menu Portaria' WHERE `id` = 96;
UPDATE `habilidades` SET `nome` = 'treinamento_portaria_insert', `descricao` = 'Pode cadastrar um Portaria' WHERE `id` = 97;
UPDATE `habilidades` SET `nome` = 'treinamento_portaria_update', `descricao` = 'Pode alterar um Portaria' WHERE `id` = 98;
UPDATE `habilidades` SET `nome` = 'admissao_pos_admissao', `descricao` = 'Acessar rota/menu Pós-Admissão' WHERE `id` = 99;
UPDATE `habilidades` SET `nome` = 'admissao_pos_admissao_insert', `descricao` = 'Pode cadastrar um Pós-Admissão' WHERE `id` = 100;
UPDATE `habilidades` SET `nome` = 'admissao_pos_admissao_update', `descricao` = 'Pode alterar um Pós-Admissão' WHERE `id` = 101;
UPDATE `habilidades` SET `nome` = 'treinamento_certificado', `descricao` = 'Acessar rota/menu Certificado' WHERE `id` = 102;
UPDATE `habilidades` SET `nome` = 'treinamento_certificado_insert', `descricao` = 'Pode cadastrar um Certificado' WHERE `id` = 103;
UPDATE `habilidades` SET `nome` = 'treinamento_certificado_update', `descricao` = 'Pode alterar um Certificado' WHERE `id` = 104;
UPDATE `habilidades` SET `nome` = 'posadmissao_form_rh', `descricao` = 'Acessar formulario pos-admissao rh' WHERE `id` = 105;
UPDATE `habilidades` SET `nome` = 'posadmissao_form_adm', `descricao` = 'Acessar formulario pos-admissao adm' WHERE `id` = 106;
UPDATE `habilidades` SET `nome` = 'posadmissao_form_ssma', `descricao` = 'Acessar formulario pos-admissao ssma' WHERE `id` = 107;
UPDATE `habilidades` SET `nome` = 'posadmissao_avaliar', `descricao` = 'Acessar formulario avaliar' WHERE `id` = 108;
UPDATE `habilidades` SET `nome` = 'posadmissao_avaliar_insert', `descricao` = 'Pode cadastrar avaliação' WHERE `id` = 109;
UPDATE `habilidades` SET `nome` = 'posadmissao_avaliar_update', `descricao` = 'Pode alterar avaliação' WHERE `id` = 110;
UPDATE `habilidades` SET `nome` = 'posadmissao_desmobilizar', `descricao` = 'Acessar formulario desmobilizar' WHERE `id` = 111;
UPDATE `habilidades` SET `nome` = 'posadmissao_desmobilizar_insert', `descricao` = 'Pode cadastrar desmobilização' WHERE `id` = 112;
UPDATE `habilidades` SET `nome` = 'posadmissao_desmobilizar_update', `descricao` = 'Pode alterar desmobilização' WHERE `id` = 113;
UPDATE `habilidades` SET `nome` = 'posadmissao_entrevista_desligamento', `descricao` = 'Acessar formulario de entrevista desligamento' WHERE `id` = 114;
UPDATE `habilidades` SET `nome` = 'posadmissao_entrevista_desligamento_insert', `descricao` = 'Pode cadastrar entrevista desligamento' WHERE `id` = 115;
UPDATE `habilidades` SET `nome` = 'posadmissao_entrevista_desligamento_update', `descricao` = 'Pode alterar entrevista desligamento' WHERE `id` = 116;
UPDATE `habilidades` SET `nome` = 'entrevista_rh_cliente', `descricao` = 'Acessar menu EntrevistaRH cliente' WHERE `id` = 117;
UPDATE `habilidades` SET `nome` = 'entrevista_rh_cliente_insert', `descricao` = 'Pode cadastrar EntrevistaRH cliente' WHERE `id` = 118;
UPDATE `habilidades` SET `nome` = 'entrevista_rh_cliente_update', `descricao` = 'Pode alterar EntrevistaRH cliente' WHERE `id` = 119;
UPDATE `habilidades` SET `nome` = 'entrevista_gestor_cliente', `descricao` = 'Acessar menu EntrevistaGestor cliente' WHERE `id` = 120;
UPDATE `habilidades` SET `nome` = 'entrevista_gestor_cliente_insert', `descricao` = 'Pode cadastrar EntrevistaGestor cliente' WHERE `id` = 121;
UPDATE `habilidades` SET `nome` = 'entrevista_gestor_cliente_update', `descricao` = 'Pode alterar EntrevistaGestor cliente' WHERE `id` = 122;
UPDATE `habilidades` SET `nome` = 'visualiza_cliente_55', `descricao` = 'Acessar menu 55Solucoes' WHERE `id` = 123;
UPDATE `habilidades` SET `nome` = 'visualiza_cliente_montisol', `descricao` = 'Acessar menu MONTISOL' WHERE `id` = 124;
UPDATE `habilidades` SET `nome` = 'visualiza_cliente_cmpc', `descricao` = 'Acessar menu CMPC' WHERE `id` = 125;
UPDATE `habilidades` SET `nome` = 'visualiza_cliente_cimar', `descricao` = 'Acessar menu CIMAR' WHERE `id` = 126;
UPDATE `habilidades` SET `nome` = 'visualiza_cliente_brk', `descricao` = 'Acessar menu BRK' WHERE `id` = 127;
UPDATE `habilidades` SET `nome` = 'admissao_cih', `descricao` = 'Acessar menu Apontamento - CIH' WHERE `id` = 128;
UPDATE `habilidades` SET `nome` = 'admissao_cih_lancar', `descricao` = 'Pode lançar uma ocorrencia CIH' WHERE `id` = 129;
UPDATE `habilidades` SET `nome` = 'admissao_cih_aprovar', `descricao` = 'Pode aprovar uma ocorrencia CIH' WHERE `id` = 130;
UPDATE `habilidades` SET `nome` = 'admissao_historico', `descricao` = 'Acessar menu Historico' WHERE `id` = 131;
UPDATE `habilidades` SET `nome` = 'ocorrencia', `descricao` = 'Acessar menu Ocorrencia' WHERE `id` = 132;
UPDATE `habilidades` SET `nome` = 'ocorrencia_tag', `descricao` = 'Acessar Ocorrencia Tag' WHERE `id` = 133;
UPDATE `habilidades` SET `nome` = 'ocorrencia_setor', `descricao` = 'Acessar Ocorrencia Setor' WHERE `id` = 134;
UPDATE `habilidades` SET `nome` = 'avaliacao_noventa', `descricao` = 'Acessar Avaliação' WHERE `id` = 135;
UPDATE `habilidades` SET `nome` = 'avaliacao_noventa_insert', `descricao` = 'Inserir Avaliação' WHERE `id` = 136;
UPDATE `habilidades` SET `nome` = 'cadastro_beneficio', `descricao` = 'Acessar Beneficio' WHERE `id` = 137;
UPDATE `habilidades` SET `nome` = 'cadastro_beneficio_insert', `descricao` = 'Inseri Beneficio Insert' WHERE `id` = 138;
UPDATE `habilidades` SET `nome` = 'cadastro_beneficio_update', `descricao` = 'Atualiza Beneficio Update' WHERE `id` = 139;
UPDATE `habilidades` SET `nome` = 'treinamento_lista_presenca', `descricao` = 'Acessar Treinamento Lista de Presença' WHERE `id` = 140;
UPDATE `habilidades` SET `nome` = 'treinamento_lista_presenca_insert', `descricao` = 'Inseri uma lista de presença' WHERE `id` = 141;
UPDATE `habilidades` SET `nome` = 'treinamento_lista_presenca_update', `descricao` = 'Atualiza lista de presença' WHERE `id` = 142;
UPDATE `habilidades` SET `nome` = 'administracao_atareuniao', `descricao` = 'Acessar Ata Reunião' WHERE `id` = 143;
UPDATE `habilidades` SET `nome` = 'administracao_atareuniao_insert', `descricao` = 'Acessar Ata Reunião Insert' WHERE `id` = 144;
UPDATE `habilidades` SET `nome` = 'administracao_atareuniao_update', `descricao` = 'Acessar Ata Reunião Update' WHERE `id` = 145;
UPDATE `habilidades` SET `nome` = 'admissao_pre_admissao', `descricao` = 'Acessar Menu Pré Admissão' WHERE `id` = 146;
UPDATE `habilidades` SET `nome` = 'administracao_pesquisaclima', `descricao` = 'Acessar Pesquisa Clima' WHERE `id` = 147;
UPDATE `habilidades` SET `nome` = 'administracao_pesquisaclima_insert', `descricao` = 'Acessar Pesquisa Clima Insert' WHERE `id` = 148;
UPDATE `habilidades` SET `nome` = 'administracao_pesquisaclima_update', `descricao` = 'Acessar Pesquisa Clima Update' WHERE `id` = 149;
UPDATE `habilidades` SET `nome` = 'admissao_intermitente', `descricao` = 'Acessar Intermitentes' WHERE `id` = 150;
UPDATE `habilidades` SET `nome` = 'administracao_planejamentodiario', `descricao` = 'Acessar Planejamento Diário' WHERE `id` = 151;
UPDATE `habilidades` SET `nome` = 'medidas_administrativa_componente', `descricao` = 'Pode ver o Componente Medidas Administrativa' WHERE `id` = 152;
UPDATE `habilidades` SET `nome` = 'historico_dossie', `descricao` = 'Acessar Ata Reunião' WHERE `id` = 153;
UPDATE `habilidades` SET `nome` = 'historico_dossie_insert', `descricao` = 'Acessar Ata Reunião Insert' WHERE `id` = 154;
UPDATE `habilidades` SET `nome` = 'historico_dossie_update', `descricao` = 'Acessar Ata Reunião Update' WHERE `id` = 155;
UPDATE `habilidades` SET `nome` = 'financeiro_classificacao-plano-conta', `descricao` = 'Acessar rota/menu Classificação de planos de conta' WHERE `id` = 156;
UPDATE `habilidades` SET `nome` = 'financeiro_classificacao-plano-conta_insert', `descricao` = 'Pode cadastrar uma nova classificação de planos de conta' WHERE `id` = 157;
UPDATE `habilidades` SET `nome` = 'financeiro_classificacao-plano-conta_update', `descricao` = 'Pode alterar uma classificação de planos de conta' WHERE `id` = 158;
UPDATE `habilidades` SET `nome` = 'financeiro_classificacao-plano-conta_delete', `descricao` = 'Pode excluir uma classificação de planos de conta' WHERE `id` = 159;
UPDATE `habilidades` SET `nome` = 'financeiro_plano-conta', `descricao` = 'Acessar rota/menu planos de conta' WHERE `id` = 160;
UPDATE `habilidades` SET `nome` = 'financeiro_plano-conta_insert', `descricao` = 'Pode cadastrar um novo plano de conta' WHERE `id` = 161;
UPDATE `habilidades` SET `nome` = 'financeiro_plano-conta_update', `descricao` = 'Pode alterar um plano de conta' WHERE `id` = 162;
UPDATE `habilidades` SET `nome` = 'financeiro_plano-conta_delete', `descricao` = 'Pode excluir um plano de conta' WHERE `id` = 163;
UPDATE `habilidades` SET `nome` = 'financeiro_formas-pagamento', `descricao` = 'Acessar rota/menu formas de pagamento' WHERE `id` = 164;
UPDATE `habilidades` SET `nome` = 'financeiro_formas-pagamento_insert', `descricao` = 'Pode cadastrar uma nova forma de pagamento' WHERE `id` = 165;
UPDATE `habilidades` SET `nome` = 'financeiro_formas-pagamento_update', `descricao` = 'Pode alterar uma nova forma de pagamento' WHERE `id` = 166;
UPDATE `habilidades` SET `nome` = 'financeiro_formas-pagamento_delete', `descricao` = 'Pode excluir uma nova forma de pagamento' WHERE `id` = 167;
UPDATE `habilidades` SET `nome` = 'financeiro_fluxo-caixa', `descricao` = 'Acessar rota/menu fluxo de caixa' WHERE `id` = 168;
UPDATE `habilidades` SET `nome` = 'financeiro_fluxo-caixa_insert', `descricao` = 'Pode cadastrar um novo lançamento' WHERE `id` = 169;
UPDATE `habilidades` SET `nome` = 'financeiro_fluxo-caixa_update', `descricao` = 'Pode alterar um lançamento' WHERE `id` = 170;
UPDATE `habilidades` SET `nome` = 'financeiro_fluxo-caixa_delete', `descricao` = 'Pode excluir um lançamento' WHERE `id` = 171;
UPDATE `habilidades` SET `nome` = 'privilegio_realizar-lancamento', `descricao` = 'Definir lançamento como realizado ou não' WHERE `id` = 172;
UPDATE `habilidades` SET `nome` = 'cadastro_instrutor', `descricao` = 'Acessar Cadastro Instrutor' WHERE `id` = 173;
UPDATE `habilidades` SET `nome` = 'cadastro_instrutor_insert', `descricao` = 'Inseri Cadastro Instrutor Insert' WHERE `id` = 174;
UPDATE `habilidades` SET `nome` = 'cadastro_instrutor_update', `descricao` = 'Atualiza Cadastro Instrutor Update' WHERE `id` = 175;
UPDATE `habilidades` SET `nome` = 'cadastro_departamento', `descricao` = 'Acessar Cadastro Departamento' WHERE `id` = 176;
UPDATE `habilidades` SET `nome` = 'cadastro_departamento_insert', `descricao` = 'Inseri Cadastro Departamento Insert' WHERE `id` = 177;
UPDATE `habilidades` SET `nome` = 'cadastro_departamento_update', `descricao` = 'Atualiza Cadastro Departamento Update' WHERE `id` = 178;
UPDATE `habilidades` SET `nome` = 'cadastro_treinamento_industria', `descricao` = 'Acessar Cadastro Treinamento Industria' WHERE `id` = 179;
UPDATE `habilidades` SET `nome` = 'cadastro_treinamento_industria_insert', `descricao` = 'Inseri Cadastro Treinamento Industria Insert' WHERE `id` = 180;
UPDATE `habilidades` SET `nome` = 'cadastro_treinamento_industria_update', `descricao` = 'Atualiza Cadastro Treinamento Industria Update' WHERE `id` = 181;
UPDATE `habilidades` SET `nome` = 'cadastro_treinamento_sgi', `descricao` = 'Acessar Cadastro Treinamento SGI' WHERE `id` = 182;
UPDATE `habilidades` SET `nome` = 'cadastro_treinamento_sgi_insert', `descricao` = 'Inseri Cadastro Treinamento SGI Insert' WHERE `id` = 183;
UPDATE `habilidades` SET `nome` = 'cadastro_treinamento_sgi_update', `descricao` = 'Atualiza Cadastro Treinamento SGI Update' WHERE `id` = 184;
UPDATE `habilidades` SET `nome` = 'cadastro_empresa_treinamento', `descricao` = 'Acessar Cadastro Empresa Treinamento' WHERE `id` = 185;
UPDATE `habilidades` SET `nome` = 'cadastro_empresa_treinamento_insert', `descricao` = 'Inseri Cadastro Empresa Treinamento Insert' WHERE `id` = 186;
UPDATE `habilidades` SET `nome` = 'cadastro_empresa_treinamento_update', `descricao` = 'Atualiza Cadastro Empresa Treinamento Update' WHERE `id` = 187;
UPDATE `habilidades` SET `nome` = 'cadastro_provas', `descricao` = 'Acessar Cadastro Provas' WHERE `id` = 188;
UPDATE `habilidades` SET `nome` = 'cadastro_provas_insert', `descricao` = 'Inseri Cadastro Provas Insert' WHERE `id` = 189;
UPDATE `habilidades` SET `nome` = 'cadastro_provas_update', `descricao` = 'Atualiza Cadastro Provas Update' WHERE `id` = 190;
UPDATE `habilidades` SET `nome` = 'administracao_aniversariantes', `descricao` = 'Acessar Aniversariantes' WHERE `id` = 191;
UPDATE `habilidades` SET `nome` = 'administracao_aniversariantes_enviar', `descricao` = 'Enviar Email Para os Aniversariantes' WHERE `id` = 192;
UPDATE `habilidades` SET `nome` = 'relatorio_relatorios', `descricao` = 'Acessar Relatórios' WHERE `id` = 193;
UPDATE `habilidades` SET `nome` = 'relatorio_controleusuarios', `descricao` = 'Acessar Controle de Usuarios' WHERE `id` = 194;
UPDATE `habilidades` SET `nome` = 'planejamento_requisicao_vaga', `descricao` = 'Acessa menu Requisição de Vaga dentro do menu Planejamento' WHERE `id` = 195;
UPDATE `habilidades` SET `nome` = 'planejamento_requisicao_vaga_insert', `descricao` = 'Inseri' WHERE `id` = 196;
UPDATE `habilidades` SET `nome` = 'weekly-report', `descricao` = 'Acessar rota Weekley report' WHERE `id` = 197;
UPDATE `habilidades` SET `nome` = 'quadro_insert', `descricao` = 'Pode criar um novo quadro no Weekly report' WHERE `id` = 198;
UPDATE `habilidades` SET `nome` = 'quadro_update', `descricao` = 'Pode alterar um quadro no Weekly report' WHERE `id` = 199;
UPDATE `habilidades` SET `nome` = 'quadro_delete', `descricao` = 'Pode excluir um quadro no Weekly report' WHERE `id` = 200;
UPDATE `habilidades` SET `nome` = 'lista_insert', `descricao` = 'Pode criar uma nova lista de tarefas em um quadro no Weekly report' WHERE `id` = 201;
UPDATE `habilidades` SET `nome` = 'lista_update', `descricao` = 'Pode editar uma lista de tarefas em um quadro no Weekly report' WHERE `id` = 202;
UPDATE `habilidades` SET `nome` = 'lista_delete', `descricao` = 'Pode excluir uma lista de tarefas em um quadro no Weekly report' WHERE `id` = 203;
UPDATE `habilidades` SET `nome` = 'tarefa_insert', `descricao` = 'Pode criar uma nova tarefa em Weekly report' WHERE `id` = 204;
UPDATE `habilidades` SET `nome` = 'tarefa_update', `descricao` = 'Pode editar título e descrição de uma tarefa em Weekly report' WHERE `id` = 205;
UPDATE `habilidades` SET `nome` = 'tarefa_delete', `descricao` = 'Pode excluir uma tarefa em Weekly report' WHERE `id` = 206;
UPDATE `habilidades` SET `nome` = 'cadastro_areaetiqueta', `descricao` = 'Acessar rota Area Etiquetas' WHERE `id` = 207;
UPDATE `habilidades` SET `nome` = 'cadastro_centrocusto', `descricao` = 'Acessar a rota Centro de Custo' WHERE `id` = 208;
UPDATE `habilidades` SET `nome` = 'cadastro_centrocusto_insert', `descricao` = 'Pode criar uma nova centrocusto' WHERE `id` = 209;
UPDATE `habilidades` SET `nome` = 'cadastro_centrocusto_update', `descricao` = 'Pode editar um centrocusto' WHERE `id` = 210;
UPDATE `habilidades` SET `nome` = 'controle_ponto_config_empresa', `descricao` = 'Acesso a tela de configurações da empresa' WHERE `id` = 211;
UPDATE `habilidades` SET `nome` = 'controle_ponto_perimetros', `descricao` = 'Acessar a rota de perímetros' WHERE `id` = 212;
UPDATE `habilidades` SET `nome` = 'controle_ponto_perimetros_insert', `descricao` = 'Pode cadastrar perímetros da empresa' WHERE `id` = 213;
UPDATE `habilidades` SET `nome` = 'controle_ponto_perimetros_update', `descricao` = 'Pode editar perímetros da empresa' WHERE `id` = 214;
UPDATE `habilidades` SET `nome` = 'controle_ponto_perimetros_delete', `descricao` = 'Pode excluir perímetros da empresa' WHERE `id` = 215;
UPDATE `habilidades` SET `nome` = 'controle_ponto_perimetros_funcionarios', `descricao` = 'Pode associar perímetros aos funcionários' WHERE `id` = 216;
UPDATE `habilidades` SET `nome` = 'controle_ponto_ocorrencias_jornadas', `descricao` = 'Acesso a tela de ocorrências de jornadas' WHERE `id` = 217;
UPDATE `habilidades` SET `nome` = 'controle_ponto_ocorrencias_jornadas_insert', `descricao` = 'Pode cadastrar uma ocorrência de jornadas' WHERE `id` = 218;
UPDATE `habilidades` SET `nome` = 'controle_ponto_ocorrencias_jornadas_update', `descricao` = 'Pode editar uma ocorrência de jornadas' WHERE `id` = 219;
UPDATE `habilidades` SET `nome` = 'controle_ponto_ocorrencias_jornadas_delete', `descricao` = 'Pode excluir ocorrência de jornadas' WHERE `id` = 220;
UPDATE `habilidades` SET `nome` = 'controle_ponto_escalas', `descricao` = 'Acesso a tela de escalas' WHERE `id` = 221;
UPDATE `habilidades` SET `nome` = 'controle_ponto_escalas_insert', `descricao` = 'Pode cadastrar uma escala' WHERE `id` = 222;
UPDATE `habilidades` SET `nome` = 'controle_ponto_escalas_update', `descricao` = 'Pode editar uma escala' WHERE `id` = 223;
UPDATE `habilidades` SET `nome` = 'controle_ponto_escalas_delete', `descricao` = 'Pode excluir escala' WHERE `id` = 224;
UPDATE `habilidades` SET `nome` = 'controle_ponto_escalas_funcionarios', `descricao` = 'Pode associar escala aos funcionários' WHERE `id` = 225;
UPDATE `habilidades` SET `nome` = 'controle_ponto_ponto-eletronico', `descricao` = 'O usuáro terá que bater ponto nas escalas definidas' WHERE `id` = 226;
UPDATE `habilidades` SET `nome` = 'controle_ponto_ajustar-jornadas', `descricao` = 'Pode fazer correções/ajuste nas jornadas de trabalho já registradas' WHERE `id` = 227;
UPDATE `habilidades` SET `nome` = 'controle_ponto_folha-ponto', `descricao` = 'Pode verificar e imprimir a folha de ponto do funcionário' WHERE `id` = 228;
UPDATE `habilidades` SET `nome` = 'controle_ponto_feriados', `descricao` = 'Acessar rota/menu feriados' WHERE `id` = 229;
UPDATE `habilidades` SET `nome` = 'controle_ponto_feriados_insert', `descricao` = 'Pode cadastrar feriados' WHERE `id` = 230;
UPDATE `habilidades` SET `nome` = 'controle_ponto_feriados_update', `descricao` = 'Pode alterar feriados' WHERE `id` = 231;
UPDATE `habilidades` SET `nome` = 'controle_ponto_feriados_delete', `descricao` = 'Pode apagar feriados' WHERE `id` = 232;
UPDATE `habilidades` SET `nome` = 'cadastro_empresa_exame', `descricao` = 'Acessar rota/menu empresa_exame' WHERE `id` = 233;
UPDATE `habilidades` SET `nome` = 'cadastro_empresa_exame_insert', `descricao` = 'Pode cadastrar empresa_exame' WHERE `id` = 234;
UPDATE `habilidades` SET `nome` = 'cadastro_empresa_exame_update', `descricao` = 'Pode alterar empresa_exame' WHERE `id` = 235;
UPDATE `habilidades` SET `nome` = 'cadastro_empresa_exame_delete', `descricao` = 'Pode apagar feriados' WHERE `id` = 236;
UPDATE `habilidades` SET `nome` = 'cadastro_empresa_exame', `descricao` = 'Acessar rota/menu empresa_exame' WHERE `id` = 237;
UPDATE `habilidades` SET `nome` = 'cadastro_empresa_exame_insert', `descricao` = 'Pode cadastrar empresa_exame' WHERE `id` = 238;
UPDATE `habilidades` SET `nome` = 'cadastro_empresa_exame_update', `descricao` = 'Pode alterar empresa_exame' WHERE `id` = 239;
UPDATE `habilidades` SET `nome` = 'cadastro_empresa_exame_delete', `descricao` = 'Pode apagar feriados' WHERE `id` = 240;
UPDATE `habilidades` SET `nome` = 'privilegio_aprovar_por_gestor', `descricao` = 'Aprovação de Gestor' WHERE `id` = 241;
UPDATE `habilidades` SET `nome` = 'privilegio_aprovar_por_rh', `descricao` = 'aprovação por RH' WHERE `id` = 242;
UPDATE `habilidades` SET `nome` = 'privilegio_gestao_rh', `descricao` = 'Permissão para RH aprovar' WHERE `id` = 243;
UPDATE `habilidades` SET `nome` = 'privilegio_admissao_processo_dados_editar', `descricao` = 'pode editar processo' WHERE `id` = 244;
UPDATE `habilidades` SET `nome` = 'cloud_cadastro', `descricao` = 'Acessar rota/menu Cloud Cadastro' WHERE `id` = 245;
UPDATE `habilidades` SET `nome` = 'cloud_cadastro_insert', `descricao` = 'Pode cadastrar um Cloud' WHERE `id` = 246;
UPDATE `habilidades` SET `nome` = 'cloud_cadastro_update', `descricao` = 'Pode alterar ativar e desativar um Cloud' WHERE `id` = 247;
UPDATE `habilidades` SET `nome` = 'cloud_cadastro_delete', `descricao` = 'Pode apagar um Cloud ' WHERE `id` = 248;
UPDATE `habilidades` SET `nome` = 'admissao_controle_exames', `descricao` = 'Admissao Menu Controle de Exames' WHERE `id` = 249;
UPDATE `habilidades` SET `nome` = 'privilegio_admissao_pre_admissao_reencaminhar_email', `descricao` = 'Pre admissao reencaminhar e-mail' WHERE `id` = 250;
UPDATE `habilidades` SET `nome` = 'cadastro_empresa_temporaria', `descricao` = 'Acessar rota/menu empresa_temporaria' WHERE `id` = 251;
UPDATE `habilidades` SET `nome` = 'cadastro_empresa_temporaria_insert', `descricao` = 'Pode cadastrar empresa_temporaria' WHERE `id` = 252;
UPDATE `habilidades` SET `nome` = 'cadastro_empresa_temporaria_update', `descricao` = 'Pode alterar empresa_temporaria' WHERE `id` = 253;
UPDATE `habilidades` SET `nome` = 'cadastro_empresa_temporaria_delete', `descricao` = 'Pode apagar empresa_temporaria' WHERE `id` = 254;
UPDATE `habilidades` SET `nome` = 'acesso_clinica', `descricao` = 'Acesso clinica' WHERE `id` = 255;
UPDATE `habilidades` SET `nome` = 'acesso_clinica_insert', `descricao` = 'Pode cadastrar exame' WHERE `id` = 256;
UPDATE `habilidades` SET `nome` = 'acesso_clinica_update', `descricao` = 'Pode alterar exame' WHERE `id` = 257;
UPDATE `habilidades` SET `nome` = 'cadastro_projetos', `descricao` = 'Acesso ao menu Projeto' WHERE `id` = 258;
UPDATE `habilidades` SET `nome` = 'cadastro_projetos_insert', `descricao` = 'Pode cadastrar Projeto' WHERE `id` = 259;
UPDATE `habilidades` SET `nome` = 'cadastro_projetos_update', `descricao` = 'Pode alterar Projeto' WHERE `id` = 260;
UPDATE `habilidades` SET `nome` = 'planejamento_mobilizacao', `descricao` = 'Acesso ao menu Mobilização dentro de Planejamento' WHERE `id` = 261;
