<table>
    <thead>
    <tr>
        <td>Id</td>
        <td>nome</td>
        <td>cpf</td>
        <td>nis</td>
        <td>nascimento</td>
        <td>sexo</td>
        <td>racaecor</td>
        <td>estadocivil</td>
        <td>conjuge</td>
        <td>conjuge_cpf</td>
        <td>conjuge_rg</td>
        <td>conjuge_nascimento</td>
        <td>pai</td>
        <td>mae</td>
        <td>nacionalidade</td>
        <td>naturalidade</td>
        <td>escolaridade_id</td>
        <td>graduacao</td>
        <td>sapato</td>
        <td>camisa</td>
        <td>calca</td>
        <td>altura</td>
        <td>peso</td>
        <td>cabelos</td>
        <td>olhos</td>
        <td>sinais</td>
        <td>deficiente</td>
        <td>deficiencia_obs</td>
        <td>ctps_numero</td>
        <td>ctps_serie</td>
        <td>ctps_uf</td>
        <td>ctps_emissao</td>
        <td>tituloeleitoral</td>
        <td>tituloeleitoral_zona</td>
        <td>tituloeleitoral_secao</td>
        <td>reservista</td>
        <td>reservista_categoria</td>
        <td>doc_tipo</td>
        <td>doc_numero</td>
        <td>doc_emissor</td>
        <td>doc_emissao</td>
        <td>doc_validade</td>
        <td>residencia</td>
        <td>comprada_fgts</td>
        <td>reside_exterior</td>
        <td>email</td>
        <td>cep</td>
        <td>logradouro</td>
        <td>end_numero</td>
        <td>complemento</td>
        <td>bairro</td>
        <td>municipio</td>
        <td>uf</td>
        <td>chegada_brasil</td>
        <td>naturalizacao_brasil</td>
        <td>casado_brasil</td>
        <td>filho_brasil</td>
        <td>banco_id</td>
        <td>tipo_conta</td>
        <td>agencia</td>
        <td>numero</td>
        <td>nome_conta</td>
        <td>vale_transporte == 1 ? 'sim' : 'não'</td>
        <td>vale_transporte_linhaum</td>
        <td>vale_transporte_linhadois</td>
        <td>primeiro_emprego</td>
        <td>desconto_plano_saude</td>
        <td>desconto_plano_saude_valor</td>
        <td>outra_empresa</td>
        <td>outra_empresa_razaosocial</td>
        <td>outra_empresa_cnpj</td>
        <td>outra_empresa_remuneracao</td>
        <td>outra_empresa_obs</td>
        <td>admissao</td>
        <td>admissional</td>
        <td>admissional_crm</td>
        <td>cargo_id</td>
        <td>cargo_descricao</td>
        <td>departamento</td>
        <td>empresa_id</td>
        <td>cliente_id</td>
        <td>tipo_contrato</td>
        <td>dias_experiencia</td>
        <td>dias_prorrogacao</td>
        <td>tipo_remuneracao</td>
        <td>forma_pagamento</td>
        <td>remuneracao</td>
        <td>remuneracao_valor</td>
        <td>descontar_vt</td>
        <td>descontar_vr_va</td>
        <td>fgts</td>
        <td>fgts_admissao</td>
        <td>fgts_retratacao</td>
        <td>fgts_banco</td>
        <td>demitido</td>
        <td>demissao</td>
        <td>demissional</td>
        <td>demissional_crm</td>
        <td>ativo</td>
    </tr>
    </thead>
    <tbody>
    @foreach($resultado as $row)
        <tr>
            <td>{{$row->id}}</td>
            <td>{{$row->nome}}</td>
            <td>{{$row->cpf}}</td>
            <td>{{$row->nis}}</td>
            <td>{{$row->nascimento}}</td>
            <td>{{$row->sexo}}</td>
            <td>{{$row->racaecor}}</td>
            <td>{{$row->estadocivil}}</td>
            <td>{{$row->conjuge}}</td>
            <td>{{$row->conjuge_cpf}}</td>
            <td>{{$row->conjuge_rg}}</td>
            <td>{{$row->conjuge_nascimento}}</td>
            <td>{{$row->pai}}</td>
            <td>{{$row->mae}}</td>
            <td>{{$row->nacionalidade}}</td>
            <td>{{$row->naturalidade}}</td>
            <td>{{substr($row->Escolaridade->tipo,5)}}</td>
            <td>{{$row->graduacao}}</td>
            <td>{{$row->sapato}}</td>
            <td>{{$row->camisa}}</td>
            <td>{{$row->calca}}</td>
            <td>{{$row->altura}}</td>
            <td>{{$row->peso}}</td>
            <td>{{$row->cabelos}}</td>
            <td>{{$row->olhos}}</td>
            <td>{{$row->sinais}}</td>
            <td>{{$row->deficiente == 1 ? 'sim' : 'não'}}</td>
            <td>{{$row->deficiencia_obs}}</td>
            <td>{{$row->ctps_numero}}</td>
            <td>{{$row->ctps_serie}}</td>
            <td>{{$row->ctps_uf}}</td>
            <td>{{$row->ctps_emissao}}</td>
            <td>{{$row->tituloeleitoral}}</td>
            <td>{{$row->tituloeleitoral_zona}}</td>
            <td>{{$row->tituloeleitoral_secao}}</td>
            <td>{{$row->reservista}}</td>
            <td>{{$row->reservista_categoria}}</td>
            <td>{{$row->doc_tipo}}</td>
            <td>{{$row->doc_numero}}</td>
            <td>{{$row->doc_emissor}}</td>
            <td>{{$row->doc_emissao}}</td>
            <td>{{$row->doc_validade}}</td>
            <td>{{$row->residencia == 1 ? 'sim' : 'não'}}</td>
            <td>{{$row->comprada_fgts == 1 ? 'sim' : 'não'}}</td>
            <td>{{$row->reside_exterior == 1 ? 'sim' : 'não'}}</td>
            <td>{{$row->email}}</td>
            <td>{{$row->cep}}</td>
            <td>{{$row->logradouro}}</td>
            <td>{{$row->end_numero}}</td>
            <td>{{$row->complemento}}</td>
            <td>{{$row->bairro}}</td>
            <td>{{$row->municipio}}</td>
            <td>{{$row->uf}}</td>
            <td>{{$row->chegada_brasil}}</td>
            <td>{{$row->naturalizacao_brasil}}</td>
            <td>{{$row->casado_brasil == 1 ? 'sim' : 'não'}}</td>
            <td>{{$row->filho_brasil == 1 ? 'sim' : 'não'}}</td>
            <td>{{$row->Banco->nome}}</td>
            <td>{{$row->tipo_conta}}</td>
            <td>{{$row->agencia}}</td>
            <td>{{$row->numero}}</td>
            <td>{{$row->nome_conta}}</td>
            <td>{{$row->vale_transporte == 1 ? 'sim' : 'não'}}</td>
            <td>{{$row->vale_transporte_linhaum}}</td>
            <td>{{$row->vale_transporte_linhadois}}</td>
            <td>{{$row->primeiro_emprego}}</td>
            <td>{{$row->desconto_plano_saude}}</td>
            <td>{{$row->desconto_plano_saude_valor}}</td>
            <td>{{$row->outra_empresa == 1 ? 'sim' : 'não'}}</td>
            <td>{{$row->outra_empresa_razaosocial}}</td>
            <td>{{$row->outra_empresa_cnpj}}</td>
            <td>{{$row->outra_empresa_remuneracao}}</td>
            <td>{{$row->outra_empresa_obs}}</td>
            <td>{{$row->admissao}}</td>
            <td>{{$row->admissional}}</td>
            <td>{{$row->admissional_crm}}</td>
            <td>{{$row->cargo_id}}</td>
            <td>{{$row->cargo_descricao}}</td>
            <td>{{$row->departamento}}</td>
            <td>{{$row->Empresa->razao_social}}</td>
            <td>{{$row->cliente->tipo == 'pessoa_juridica' ? $row->cliente->clientepj->razaosocial : $row->cliente->clientepf->nome}}</td>
            <td>{{$row->tipo_contrato}}</td>
            <td>{{$row->dias_experiencia}}</td>
            <td>{{$row->dias_prorrogacao}}</td>
            <td>{{$row->tipo_remuneracao}}</td>
            <td>{{$row->forma_pagamento}}</td>
            <td>{{$row->remuneracao}}</td>
            <td>{{$row->remuneracao_valor}}</td>
            <td>{{$row->descontar_vt == 1 ? 'sim' : 'não'}}</td>
            <td>{{$row->descontar_vr_va == 1 ? 'sim' : 'não'}}</td>
            <td>{{$row->fgts == 1 ? 'sim' : 'não'}}</td>
            <td>{{$row->fgts_admissao}}</td>
            <td>{{$row->fgts_retratacao}}</td>
            <td>{{$row->fgts_banco}}</td>
            <td>{{$row->demitido == 1 ? 'sim' : 'não'}}</td>
            <td>{{$row->demissao}}</td>
            <td>{{$row->demissional}}</td>
            <td>{{$row->demissional_crm}}</td>
            <td>{{$row->ativo == 1 ? 'sim' : 'não'}}</td>
        </tr>
    @endforeach
    </tbody>
</table>
