<?php

namespace App\Authorization\Catalog;

use App\Authorization\HabilidadeDefinition;
use App\Authorization\HabilidadeMetaParser;

/**
 * Catálogo tipado gerado a partir do HabilidadesTableSeeder (exceto piloto).
 * Labels via HabilidadeMetaParser; piloto permanece nos catalogs dedicados.
 *
 * Regenerar: php artisan habilidades:regenerar-completo-catalog
 */
final class CompletoCatalog
{
    /**
     * @return list<HabilidadeDefinition>
     */
    public static function definitions(): array
    {
        $defs = [];
        foreach (self::entries() as [$nome, $descricao]) {
            $defs[] = HabilidadeMetaParser::toDefinition($nome, $descricao);
        }

        return $defs;
    }

    /**
     * @return list<array{0: string, 1: string}>
     */
    private static function entries(): array
    {
        return [
            ['usuario_usuarios', 'Acessar rota/menu usuários'],
            ['usuario_usuarios_insert', 'Pode cadastrar um usuário'],
            ['usuario_usuarios_update', 'Pode alterar um usuário'],
            ['usuario_usuarios_delete', 'Pode apagar um usuário'],
            ['usuario_alterar-senha', 'Pode alterar sua propria senha de acesso ao sistema'],
            ['administracao_clientes', 'Acessar rota/menu clientes'],
            ['administracao_clientes_insert', 'Pode cadastrar um cliente'],
            ['administracao_clientes_update', 'Pode alterar um cliente'],
            ['administracao_clientes_delete', 'Pode apagar um cliente'],
            ['administracao_documentos_legais', 'Acessar rota/menu documentos legais'],
            ['administracao_documentos_legais_insert', 'Pode cadastrar um documento legal'],
            ['administracao_documentos_legais_update', 'Pode alterar um documento legal'],
            ['administracao_documentos_legais_delete', 'Pode apagar um documento legal'],
            ['administracao_documentos_legais_contrato', 'Acessar rota/menu contrato de documentos legais'],
            ['administracao_documentos_legais_contrato_insert', 'Pode cadastrar contratos em documentos legais'],
            ['administracao_documentos_legais_contrato_update', 'Pode alterar contratos em documentos legais'],
            ['administracao_documentos_legais_contrato_delete', 'Pode apagar contratos em documentos legais'],
            ['administracao_documentos_legais_contrato_show', 'Pode visualizar contratos em documentos legais'],
            ['administracao_documentos_legais_contrato_pdf', 'Exportar contrato em pdf em documentos legais'],
            ['administracao_documentos_legais_documentos_empresa', 'Acessar rota/menu documentos empresa de documentos legais'],
            ['administracao_documentos_legais_documentos_empresa_insert', 'Pode cadastrar documentos empresa em documentos legais'],
            ['administracao_documentos_legais_documentos_empresa_update', 'Pode alterar documentos empresa em documentos legais'],
            ['administracao_documentos_legais_documentos_empresa_delete', 'Pode apagar documentos empresa em documentos legais'],
            ['administracao_documentos_legais_documentos_empresa_show', 'Pode visualizar documentos empresa em documentos legais'],
            ['administracao_documentos_legais_documentos_empresa_pdf', 'Exportar documentos empresa em pdf em documentos legais'],
            ['administracao_documentos_legais_documentos_ssma', 'Acessar rota/menu documentos ssma de documentos legais'],
            ['administracao_documentos_legais_documentos_ssma_insert', 'Pode cadastrar documentos ssma em documentos legais'],
            ['administracao_documentos_legais_documentos_ssma_update', 'Pode alterar documentos ssma em documentos legais'],
            ['administracao_documentos_legais_documentos_ssma_delete', 'Pode apagar documentos ssma em documentos legais'],
            ['administracao_documentos_legais_documentos_ssma_show', 'Pode visualizar documentos ssma em documentos legais'],
            ['administracao_documentos_legais_documentos_ssma_pdf', 'Exportar documentos ssma em pdf em documentos legais'],
            ['administracao_documentos_legais_tipos_documentos', 'Acessar rota/menu tipos documentos de documentos legais'],
            ['administracao_documentos_legais_tipos_documentos_insert', 'Pode cadastrar tipos documentos em documentos legais'],
            ['administracao_documentos_legais_tipos_documentos_update', 'Pode alterar tipos documentos em documentos legais'],
            ['administracao_documentos_legais_tipos_documentos_delete', 'Pode apagar tipos documentos em documentos legais'],
            ['administracao_documentos_legais_tipos_servicos', 'Acessar rota/menu tipos serviços de documentos legais'],
            ['administracao_documentos_legais_tipos_servicos_insert', 'Pode cadastrar tipos serviços em documentos legais'],
            ['administracao_documentos_legais_tipos_servicos_update', 'Pode alterar tipos serviços em documentos legais'],
            ['administracao_documentos_legais_tipos_servicos_delete', 'Pode apagar tipos serviços em documentos legais'],
            ['administracao_documentos_legais_formas_contratos', 'Acessar rota/menu formas contratos de documentos legais'],
            ['administracao_documentos_legais_formas_contratos_insert', 'Pode cadastrar formas contratos em documentos legais'],
            ['administracao_documentos_legais_formas_contratos_update', 'Pode alterar formas contratos em documentos legais'],
            ['administracao_documentos_legais_formas_contratos_delete', 'Pode apagar formas contratos em documentos legais'],
            ['curriculos_recrutamento', 'Acessar rota/menu curriculos recrutamento'],
            ['curriculos_recrutamento_insert', 'Pode cadastrar um curriculo recrutamento'],
            ['curriculos_recrutamento_update', 'Pode alterar um curriculo recrutamento'],
            ['curriculos_recrutamento_delete', 'Pode apagar um curriculo recrutamento'],
            ['curriculos_selecionados', 'Pode acessar menu curriculo'],
            ['feedback_curriculos', 'Acessar rota/menu Feedback Curriculos'],
            ['feedback_curriculos_insert', 'Pode cadastrar um Feedback Curriculo'],
            ['feedback_curriculos_update', 'Pode alterar um Feedback Curriculo'],
            ['feedback_curriculos_delete', 'Pode apagar um Feedback Curriculo'],
            ['entrevista_parecer_rh', 'Acessar rota/menu Parecer Rh'],
            ['entrevista_parecer_rh_insert', 'Pode cadastrar um Parecer Rh'],
            ['entrevista_parecer_rh_update', 'Pode alterar um Parecer Rh'],
            ['entrevista_parecer_rh_delete', 'Pode apagar um Parecer Rh'],
            ['entrevista_parecer_rota', 'Acessar rota/menu Parecer Rota Transporte'],
            ['entrevista_parecer_rota_insert', 'Pode cadastrar um Parecer Rota Transporte'],
            ['entrevista_parecer_rota_update', 'Pode alterar um Parecer Rota Transporte'],
            ['entrevista_parecer_rota_delete', 'Pode apagar um Parecer Rota Transporte'],
            ['entrevista_parecer_teste_pratico', 'Acessar rota/menu Parecer Teste Prático'],
            ['entrevista_parecer_teste_pratico_insert', 'Pode cadastrar um Parecer Teste Prático'],
            ['entrevista_parecer_teste_pratico_update', 'Pode alterar um Parecer Teste Prático'],
            ['entrevista_parecer_teste_pratico_delete', 'Pode apagar um Parecer Teste Prático'],
            ['entrevista_parecer_entrevista', 'Acessar rota/menu Parecer Entrevistas Técnicas'],
            ['entrevista_parecer_entrevista_insert', 'Pode cadastrar um Parecer Entrevista Técnica'],
            ['entrevista_parecer_entrevista_update', 'Pode alterar um Parecer Entrevista Técnica'],
            ['entrevista_parecer_entrevista_delete', 'Pode apagar um Parecer Entrevista Técnica'],
            ['entrevista_resultado_integrado', 'Acessar rota/menu Resultados Integrados'],
            ['entrevista_resultado_integrado_insert', 'Pode cadastrar um Resultado'],
            ['entrevista_resultado_integrado_update', 'Pode alterar um Resultado'],
            ['entrevista_resultado_integrado_delete', 'Pode apagar um Resultado'],
            ['admissao_processo', 'Acessar rota/menu Admissões'],
            ['admissao_processo_insert', 'Pode cadastrar um Admissão'],
            ['admissao_processo_update', 'Pode alterar um Admissão'],
            ['admissao_processo_delete', 'Pode apagar um Admissão'],
            ['admissao_importacao', 'Acessar rota/menu Importação de Admissões'],
            ['admissao_controle_exames', 'Acessar menu Controle de Exames'],
            ['cloud', 'Acessar rota/menu Cloud'],
            ['cloud_insert', 'Pode cadastrar um Cloud'],
            ['cloud_update', 'Pode alterar um Cloud'],
            ['cloud_delete', 'Pode apagar um Cloud'],
            ['cloud_cadastro', 'Acessar rota/menu Cloud Cadastro'],
            ['cloud_cadastro_insert', 'Pode cadastrar um Cloud'],
            ['cloud_cadastro_update', 'Pode alterar ativar e desativar um Cloud'],
            ['cloud_cadastro_delete', 'Pode apagar um Cloud '],
            ['cloud_configuracoes', 'Acessar rota/menu Cloud Configurações'],
            ['cloud_configuracoes_insert', 'Pode cadastrar um Cloud Configurações'],
            ['cloud_configuracoes_update', 'Pode alterar um Cloud Configurações'],
            ['cloud_configuracoes_delete', 'Pode apagar um Cloud Configurações'],
            ['site_galeria_site', 'Acessar rota/menu Site - Galeria'],
            ['site_galeria_site_insert', 'Pode cadastrar uma Galeria'],
            ['site_galeria_site_update', 'Pode alterar uma Galeria'],
            ['site_galeria_site_delete', 'Pode apagar uma Galeria'],
            ['site_cartela_cliente_site', 'Acessar rota/menu Site - Cartela Cliente'],
            ['site_cartela_cliente_site_insert', 'Pode cadastrar uma Cartela Cliente'],
            ['site_cartela_cliente_site_update', 'Pode alterar uma Cartela Cliente'],
            ['site_cartela_cliente_site_delete', 'Pode apagar uma Cartela Cliente'],
            ['site_depoimento_site', 'Acessar rota/menu Site - Depoimento'],
            ['site_depoimento_site_insert', 'Pode cadastrar um Depoimento'],
            ['site_depoimento_site_update', 'Pode alterar um Depoimento'],
            ['site_depoimento_site_delete', 'Pode apagar um Depoimento'],
            ['cadastro_vagas', 'Acessar rota/menu Vagas'],
            ['cadastro_vagas_insert', 'Pode cadastrar uma vaga'],
            ['cadastro_vagas_update', 'Pode alterar uma vaga'],
            ['cadastro_vagas_abertas', 'Acessar rota/menu Vagas Abertas'],
            ['cadastro_vagas_abertas_insert', 'Pode cadastrar uma vaga aberta'],
            ['cadastro_vagas_abertas_update', 'Pode alterar uma vaga aberta'],
            ['treinamento_carteira-etiquetas', 'Acessar rota/menu Treinamentos'],
            ['treinamento_carteira-etiquetas_insert', 'Pode cadastrar um treinamento'],
            ['treinamento_carteira-etiquetas_update', 'Pode alterar um treinamento'],
            ['treinamento_envio', 'Pode enviar por email ou imprimir'],
            ['treinamento_carteira-etiquetas_retirar_treinamento_realizado', 'Pode retirar treinamento marcado como realizado'],
            ['administracao_fornecedores', 'Acessar rota/menu Fornecedores'],
            ['administracao_fornecedores_insert', 'Pode cadastrar um Fornecedor'],
            ['administracao_fornecedores_update', 'Pode alterar um Fornecedor'],
            ['administracao_fornecedores_delete', 'Pode apagar um Fornecedor'],
            ['treinamento_portaria', 'Acessar rota/menu Portaria'],
            ['treinamento_portaria_insert', 'Pode cadastrar um Portaria'],
            ['treinamento_portaria_update', 'Pode alterar um Portaria'],
            ['admissao_pos_admissao', 'Acessar rota/menu Pós-Admissão'],
            ['admissao_pos_admissao_insert', 'Pode cadastrar um Pós-Admissão'],
            ['admissao_pos_admissao_update', 'Pode alterar um Pós-Admissão'],
            ['treinamento_certificado', 'Acessar rota/menu Certificado'],
            ['treinamento_certificado_insert', 'Pode cadastrar um Certificado'],
            ['treinamento_certificado_update', 'Pode alterar um Certificado'],
            ['admissao_pos_form_rh', 'Acessar formulario pos-admissao rh'],
            ['admissao_pos_form_adm', 'Acessar formulario pos-admissao adm'],
            ['admissao_pos_form_ssma', 'Acessar formulario pos-admissao ssma'],
            ['admissao_pos_avaliar', 'Acessar formulario avaliar'],
            ['admissao_pos_avaliar_insert', 'Pode cadastrar avaliação'],
            ['admissao_pos_avaliar_update', 'Pode alterar avaliação'],
            ['admissao_pos_desmobilizar', 'Acessar formulario desmobilizar'],
            ['admissao_pos_desmobilizar_insert', 'Pode cadastrar desmobilização'],
            ['admissao_pos_desmobilizar_update', 'Pode alterar desmobilização'],
            ['admissao_pos_entrevista_desligamento', 'Acessar formulario de entrevista desligamento'],
            ['admissao_pos_entrevista_desligamento_insert', 'Pode cadastrar entrevista desligamento'],
            ['admissao_pos_entrevista_desligamento_update', 'Pode alterar entrevista desligamento'],
            ['entrevista_rh_cliente', 'Acessar menu EntrevistaRH cliente'],
            ['entrevista_rh_cliente_insert', 'Pode cadastrar EntrevistaRH cliente'],
            ['entrevista_rh_cliente_update', 'Pode alterar EntrevistaRH cliente'],
            ['entrevista_gestor_cliente', 'Acessar menu EntrevistaGestor cliente'],
            ['entrevista_gestor_cliente_insert', 'Pode cadastrar EntrevistaGestor cliente'],
            ['entrevista_gestor_cliente_update', 'Pode alterar EntrevistaGestor cliente'],
            ['admissao_historico', 'Acessar menu Historico'],
            ['admissao_historico_aba_medidas_administrativas', 'Pode ver o Componente Medidas Administrativa'],
            ['ocorrencia', 'Acessar menu Ocorrencia'],
            ['ocorrencia_tag', 'Acessar Ocorrencia Tag'],
            ['ocorrencia_setor', 'Acessar Ocorrencia Setor'],
            ['admissao_historico_aba_avaliacao_noventa_dias', 'Acessar Avaliação de Experiência'],
            ['avaliacao_noventa_insert', 'Inserir Avaliação'],
            ['cadastro_beneficio', 'Acessar Beneficio'],
            ['cadastro_beneficio_insert', 'Acessar Beneficio Insert'],
            ['cadastro_beneficio_update', 'Acessar Beneficio Update'],
            ['treinamento_lista_presenca', 'Acessar Treinamento Lista de Presença'],
            ['treinamento_lista_presenca_insert', 'Inseri uma lista de presença'],
            ['treinamento_lista_presenca_update', 'Atualiza lista de presença'],
            ['administracao_atareuniao', 'Acessar Ata Reunião'],
            ['administracao_atareuniao_insert', 'Acessar Ata Reunião Insert'],
            ['administracao_atareuniao_update', 'Acessar Ata Reunião Update'],
            ['administracao_atareuniao_privilegio_adm', 'Pode visualizar todas as Atas de Reunião'],
            ['admissao_pre_admissao', 'Acessar Menu Pré Admissão'],
            ['admissao_historico_aba_dossie', 'Acessar Dossie'],
            ['historico_dossie_insert', 'Acessar Dossie Insert'],
            ['historico_dossie_update', 'Acessar Dossie Update'],
            ['admissao_historico_aba_feedback', 'Pode Acessar aba de Feedback no historico'],
            ['admissao_historico_aba_avaliacao_anual', 'Pode Acessar aba de Avaliacao Anual no historico'],
            ['admissao_historico_aba_ferias', 'Pode Acessar aba de Ferias no historico'],
            ['admissao_historico_aba_promocao', 'Pode Acessar aba de Promocao no historico'],
            ['admissao_historico_aba_metas', 'Pode Acessar aba de Metas no historico'],
            ['admissao_historico_aba_log', 'Pode Acessar aba de Logs no historico'],
            ['admissao_historico_aba_afastamento', 'Pode Acessar aba de Afastamento no historico'],
            ['admissao_historico_filtrar_demitido', 'Acessar Usuarios Demitidos'],
            ['administracao_pesquisaclima', 'Acessar Pesquisa Clima'],
            ['administracao_pesquisaclima_insert', 'Acessar Pesquisa Clima Insert'],
            ['administracao_pesquisaclima_update', 'Acessar Pesquisa Clima Update'],
            ['admissao_intermitente', 'Acessar Intermitentes'],
            ['administracao_planejamentodiario', 'Acessar Planejamento Diário'],
            ['financeiro_classificacao-plano-conta', 'Acessar rota/menu Classificação de planos de conta'],
            ['financeiro_classificacao-plano-conta_insert', 'Pode cadastrar uma nova classificação de planos de conta'],
            ['financeiro_classificacao-plano-conta_update', 'Pode alterar uma classificação de planos de conta'],
            ['financeiro_classificacao-plano-conta_delete', 'Pode excluir uma classificação de planos de conta'],
            ['financeiro_plano-conta', 'Acessar rota/menu planos de conta'],
            ['financeiro_plano-conta_insert', 'Pode cadastrar um novo plano de conta'],
            ['financeiro_plano-conta_update', 'Pode alterar um plano de conta'],
            ['financeiro_plano-conta_delete', 'Pode excluir um plano de conta'],
            ['financeiro_formas-pagamento', 'Acessar rota/menu formas de pagamento'],
            ['financeiro_formas-pagamento_insert', 'Pode cadastrar uma nova forma de pagamento'],
            ['financeiro_formas-pagamento_update', 'Pode alterar uma nova forma de pagamento'],
            ['financeiro_formas-pagamento_delete', 'Pode excluir uma nova forma de pagamento'],
            ['financeiro_fluxo-caixa', 'Acessar rota/menu fluxo de caixa'],
            ['financeiro_fluxo-caixa_insert', 'Pode cadastrar um novo lançamento'],
            ['financeiro_fluxo-caixa_update', 'Pode alterar um lançamento'],
            ['financeiro_fluxo-caixa_delete', 'Pode excluir um lançamento'],
            ['cadastro_instrutor', 'Acessar Cadastro Instrutor'],
            ['cadastro_instrutor_insert', 'Inseri Cadastro Instrutor Insert'],
            ['cadastro_instrutor_update', 'Atualiza Cadastro Instrutor Update'],
            ['cadastro_departamento', 'Acessar Cadastro Departamento'],
            ['cadastro_departamento_insert', 'Inseri Cadastro Departamento Insert'],
            ['cadastro_departamento_update', 'Atualiza Cadastro Departamento Update'],
            ['cadastro_treinamento_industria', 'Acessar Cadastro Treinamento Industria'],
            ['cadastro_treinamento_industria_insert', 'Inseri Cadastro Treinamento Industria Insert'],
            ['cadastro_treinamento_industria_update', 'Atualiza Cadastro Treinamento Industria Update'],
            ['cadastro_treinamento_sgi', 'Acessar Cadastro Treinamento SGI'],
            ['cadastro_treinamento_sgi_insert', 'Inseri Cadastro Treinamento SGI Insert'],
            ['cadastro_treinamento_sgi_update', 'Atualiza Cadastro Treinamento SGI Update'],
            ['cadastro_carteira_assinatura', 'Cadastro Assinatura Carteira'],
            ['cadastro_empresa_treinamento', 'Acessar Cadastro Empresa Treinamento'],
            ['cadastro_empresa_treinamento_insert', 'Inseri Cadastro Empresa Treinamento Insert'],
            ['cadastro_empresa_treinamento_update', 'Atualiza Cadastro Empresa Treinamento Update'],
            ['cadastro_provas', 'Acessar Cadastro Provas'],
            ['cadastro_provas_insert', 'Inseri Cadastro Provas Insert'],
            ['cadastro_provas_update', 'Atualiza Cadastro Provas Update'],
            ['cadastro_tipos_cih', 'Pode cadastrar um tipo de CIH'],
            ['administracao_aniversariantes', 'Acessar Aniversariantes'],
            ['administracao_aniversariantes_enviar', 'Enviar Email Para os Aniversariantes'],
            ['administracao_aprovacao_extra_config', 'Acessar Configuração de Aprovações Extras'],
            ['administracao_aprovacao_extra_config_insert', 'Pode cadastrar uma Configuração de Aprovação Extra'],
            ['administracao_aprovacao_extra_config_update', 'Pode alterar uma Configuração de Aprovação Extra'],
            ['administracao_aprovacao_extra_config_delete', 'Pode apagar uma Configuração de Aprovação Extra'],
            ['cadastro_customizacoes_aprovacao_extra', 'Configurar Aprovações Extras (menu Customizações)'],
            ['cadastro_customizacoes_gestor_aprovacao', 'Configurar Gestor Aprovação (menu Customizações)'],
            ['configuracao_whatsapp', 'Configurar templates e dados de contato WhatsApp (menu Customizações)'],
            ['preferencias_notificacao_whatsapp', 'Escolher quais notificações WhatsApp deseja receber da empresa'],
            ['relatorio_relatorios', 'Acessar Relatórios'],
            ['relatorio_controleusuarios', 'Acessar Controle de Usuarios'],
            ['relatorio_asos', 'Acessar Relatorio Aso'],
            ['relatorio_medidas_administrativas', 'Acessar Relatorio Medidas Administrativas'],
            ['relatorio_treinamento', 'Acessar Relatorio de Treinamentos'],
            ['relatorio_ferias', 'Acessar Relatorio de Férias'],
            ['relatorio_centro_de_custo', 'Acessar Relatorio de Centro de Custo'],
            ['relatorio_aniversariantes', 'Acessar Relatórios de Aniversariantes'],
            ['relatorio_avaliacao_90_dias', 'Pode acessar o relatório de avaliação de 90 dias'],
            ['relatorio_nps', 'Acessar Relatório NPS (Resultados)'],
            ['planejamento_requisicao_vaga', 'Acessa menu Requisição de Vaga dentro do menu Planejamento'],
            ['planejamento_requisicao_vaga_insert', 'Inseri'],
            ['cadastro_customizacoes_requisicao_vaga', 'Configurar campos personalizados da Requisição de Vaga (menu Customizações)'],
            ['weekly_report', 'Acessar rota Weekley report'],
            ['weekly_report_quadro_insert', 'Pode criar um novo quadro no Weekly report'],
            ['weekly_report_quadro_update', 'Pode alterar um quadro no Weekly report'],
            ['weekly_report_quadro_delete', 'Pode excluir um quadro no Weekly report'],
            ['weekly_report_quadro_lista_insert', 'Pode criar uma nova lista de tarefas em um quadro no Weekly report'],
            ['weekly_report_quadro_lista_update', 'Pode editar uma lista de tarefas em um quadro no Weekly report'],
            ['weekly_report_quadro_lista_delete', 'Pode excluir uma lista de tarefas em um quadro no Weekly report'],
            ['weekly_report_quadro_tarefa_insert', 'Pode criar uma nova tarefa em Weekly report'],
            ['weekly_report_quadro_tarefa_update', 'Pode editar título e descrição de uma tarefa em Weekly report'],
            ['weekly_report_quadro_tarefa_delete', 'Pode excluir uma tarefa em Weekly report'],
            ['cadastro_areaetiqueta', 'Acessar rota Area Etiquetas'],
            ['cadastro_dossie_tipos', 'Acessar Cadastro Tipos de Dossiê'],
            ['cadastro_dossie_tipos_insert', 'Inserir Cadastro Tipos de Dossiê'],
            ['cadastro_dossie_tipos_update', 'Atualizar Cadastro Tipos de Dossiê'],
            ['cadastro_documentos_preadmissao', 'Acessar Cadastro Documentos da Pré-admissão'],
            ['cadastro_documentos_preadmissao_insert', 'Inserir Cadastro Documentos da Pré-admissão'],
            ['cadastro_documentos_preadmissao_update', 'Atualizar Cadastro Documentos da Pré-admissão'],
            ['cadastro_centrocusto', 'Acessar a rota Centro de Custo'],
            ['cadastro_centrocusto_insert', 'Pode criar uma nova centrocusto'],
            ['cadastro_centrocusto_update', 'Pode editar um centrocusto'],
            ['controle_ponto_config_empresa', 'Acesso a tela de configurações da empresa'],
            ['controle_ponto_folha_ponto_manual', 'Acesso a tela de folha de ponto manual'],
            ['controle_ponto_relatorio_sintetico', 'Acesso a tela de relatorio sintetico'],
            ['controle_ponto_perimetros', 'Acessar a rota de perímetros'],
            ['controle_ponto_perimetros_insert', 'Pode cadastrar perímetros da empresa'],
            ['controle_ponto_perimetros_update', 'Pode editar perímetros da empresa'],
            ['controle_ponto_perimetros_delete', 'Pode excluir perímetros da empresa'],
            ['controle_ponto_perimetros_funcionarios', 'Pode associar perímetros aos funcionários'],
            ['controle_ponto_ocorrencias_jornadas', 'Acesso a tela de ocorrências de jornadas'],
            ['controle_ponto_ocorrencias_jornadas_insert', 'Pode cadastrar uma ocorrência de jornadas'],
            ['controle_ponto_ocorrencias_jornadas_update', 'Pode editar uma ocorrência de jornadas'],
            ['controle_ponto_ocorrencias_jornadas_delete', 'Pode excluir ocorrência de jornadas'],
            ['controle_ponto_escalas', 'Acesso a tela de escalas'],
            ['controle_ponto_escalas_insert', 'Pode cadastrar uma escala'],
            ['controle_ponto_escalas_update', 'Pode editar uma escala'],
            ['controle_ponto_escalas_delete', 'Pode excluir escala'],
            ['controle_ponto_escalas_funcionarios', 'Pode associar escala aos funcionários'],
            ['controle_ponto_ponto-eletronico', 'O usuáro terá que bater ponto nas escalas definidas'],
            ['controle_ponto_ajustar-jornadas', 'Pode fazer correções/ajuste nas jornadas de trabalho já registradas'],
            ['controle_ponto_folha-ponto', 'Pode verificar e imprimir a folha de ponto do funcionário'],
            ['controle_ponto_folha-ponto_adm', 'Administrar e ver todas as folhas de ponto'],
            ['controle_ponto_feriados', 'Acessar rota/menu feriados'],
            ['controle_ponto_feriados_insert', 'Pode cadastrar feriados'],
            ['controle_ponto_feriados_update', 'Pode alterar feriados'],
            ['controle_ponto_feriados_delete', 'Pode apagar feriados'],
            ['cadastro_empresa_exame', 'Acessar rota/menu empresa_exame'],
            ['cadastro_empresa_exame_insert', 'Pode cadastrar empresa_exame'],
            ['cadastro_empresa_exame_update', 'Pode alterar empresa_exame'],
            ['cadastro_empresa_exame_delete', 'Pode apagar feriados'],
            ['cadastro_empresa_pcmso', 'Acessar PCMSO'],
            ['cadastro_empresa_pcmso_insert', 'Pode cadastrar um PCMSO'],
            ['cadastro_empresa_pcmso_update', 'Pode alterar um PCMSO'],
            ['cadastro_empresa_temporaria', 'Acessar rota/menu empresa_temporaria'],
            ['cadastro_empresa_temporaria_insert', 'Pode cadastrar empresa_temporaria'],
            ['cadastro_empresa_temporaria_update', 'Pode alterar empresa_temporaria'],
            ['cadastro_empresa_temporaria_delete', 'Pode apagar empresa_temporaria'],
            ['acesso_clinica', 'Acesso clinica'],
            ['acesso_clinica_insert', 'Pode cadastrar exame'],
            ['acesso_clinica_update', 'Pode alterar exame'],
            ['cadastro_empresa_temporaria_delete', 'Pode apagar empresa_temporaria'],
            ['cadastro_projetos', 'Acesso ao menu Projeto'],
            ['cadastro_projetos_insert', 'Pode cadastrar Projeto'],
            ['cadastro_projetos_update', 'Pode alterar Projeto'],
            ['cadastro_empresa_temporaria_delete', 'Pode apagar empresa_temporaria'],
            ['planejamento_mobilizacao', 'Acesso ao menu Mobilização dentro de Planejamento'],
            ['cadastro_avaliacoes', 'Pode cadastrar avaliações'],
            ['cadastro_avaliacao_tipo', 'Acessar tipos de avaliação'],
            ['cadastro_avaliacao_tipo_insert', 'Pode cadastrar tipos de avaliação'],
            ['cadastro_avaliacao_tipo_update', 'Pode alterar tipos de avaliação'],
            ['cadastro_avaliacao_tipo_show', 'Pode visualizar tipos de avaliação'],
            ['cadastro_avaliacao_tipo_active', 'Pode ativar/desativar tipos de avaliação'],
            ['cadastro_avaliador_tipo', 'Acessar tipos de avaliadores'],
            ['cadastro_avaliador_tipo_insert', 'Pode cadastrar tipos de avaliadores'],
            ['cadastro_avaliador_tipo_update', 'Pode alterar tipos de avaliadores'],
            ['cadastro_avaliador_tipo_show', 'Pode visualizar tipos de avaliadores'],
            ['cadastro_avaliador_tipo_active', 'Pode ativar/desativar tipos de avaliadores'],
            ['cadastro_avaliacao_topico', 'Acessar tópicos de avaliação'],
            ['cadastro_avaliacao_topico_insert', 'Pode cadastrar tópicos de avaliação'],
            ['cadastro_avaliacao_topico_update', 'Pode alterar tópicos de avaliação'],
            ['cadastro_avaliacao', 'Acessar cadastro de avaliações'],
            ['cadastro_avaliacao_insert', 'Pode cadastrar avaliação'],
            ['cadastro_avaliacao_update', 'Pode alterar cadastro de avaliação'],
            ['cadastro_avaliacao_active', 'Pode ativar/desativar cadastro de avaliação'],
            ['cadastro_avaliacao_vincular_avaliadores', 'Pode vincular avaliadores na avaliação'],
            ['avaliacoes_listar', 'Acessar avaliações'],
            ['avaliacoes_avaliar', 'Pode fazer avaliação'],
            ['avaliacoes_final', 'Pode fazer avaliacao final'],
            ['relatorio_efetivo', 'Pode acessar relatório de efetivo'],
            ['admissao_documentos_carta_oferta', 'Acessa Menu Carta Oferta'],
            ['admissao_documentos_carta_oferta_aprova_reprova', 'Pode Aprovar ou Reprovar uma Carta Oferta'],
            ['administracao_carta_oferta_template', 'Gerenciar template de Carta Oferta'],
            ['planejamento_movimentacao_exibir_aba_demissao', 'Exibir aba demissão'],
            ['planejamento_movimentacao_exibir_aba_ferias', 'Exibir aba férias'],
            ['planejamento_movimentacao_ferias_editar', 'Editar solicitação de férias'],
            ['planejamento_movimentacao_ferias_deletar', 'Deletar solicitação de férias'],
            ['planejamento_movimentacao_exibir_aba_admissao', 'Exibir aba admissão'],
            ['planejamento_movimentacao_exibir_aba_lideranca_de_pessoal_valor_extra', 'Exibir aba liderança de pessoal e valor extra'],
            ['planejamento_movimentacao_exibir_aba_mudanca_cargo', 'Exibir aba mudança de cargo'],
            ['planejamento_movimentacao_exibir_aba_mudanca_de_intermitente_para_fixo', 'Exibir aba mudança de intermitente'],
            ['planejamento_movimentacao_exibir_aba_transferencia', 'Exibir aba transferencia'],
        ];
    }
}
